// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// DotTag - The type of error returned
type DotTag string

const (
	DotTagMissingInputParameter DotTag = "missing_input_parameter"
	DotTagInvalidInputParameter DotTag = "invalid_input_parameter"
	DotTagNotFound              DotTag = "not_found"
)

func (e DotTag) ToPointer() *DotTag {
	return &e
}

func (e *DotTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "missing_input_parameter":
		fallthrough
	case "invalid_input_parameter":
		fallthrough
	case "not_found":
		*e = DotTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DotTag: %v", v)
	}
}

// Error - An error has occurred, and further details are contained in the response
type Error struct {
	// The type of error returned
	DotTag DotTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
