// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// GrantType - The type of OAuth 2.0 grant being utilized.
//
// The value will always be `authorization_code` when exchanging an authorization code for an access token.
type GrantType string

const (
	GrantTypeAuthorizationCode GrantType = "authorization_code"
)

func (e GrantType) ToPointer() *GrantType {
	return &e
}

func (e *GrantType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authorization_code":
		*e = GrantType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GrantType: %v", v)
	}
}

type Scope string

const (
	ScopeBoltAccountManage Scope = "bolt.account.manage"
	ScopeBoltAccountView   Scope = "bolt.account.view"
	ScopeOpenid            Scope = "openid"
)

func (e Scope) ToPointer() *Scope {
	return &e
}

func (e *Scope) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bolt.account.manage":
		fallthrough
	case "bolt.account.view":
		fallthrough
	case "openid":
		*e = Scope(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Scope: %v", v)
	}
}

type GetAccessTokenRequest struct {
	// Fetched value using OTP value from the Authorization Modal.
	Code string `form:"name=code"`
	// Merchant publishable key which can be found in the merchant dashboard
	ClientID string `form:"name=client_id"`
	// Your Bolt API Key.
	ClientSecret string `form:"name=client_secret"`
	// The type of OAuth 2.0 grant being utilized.
	//
	// The value will always be `authorization_code` when exchanging an authorization code for an access token.
	//
	GrantType GrantType `form:"name=grant_type"`
	// The scope issued to the merchant when receiving an authorization code.
	// Options include `bolt.account.manage`, `bolt.account.view`, `openid`.
	// You can find more information on these options in our
	// [OAuth scope documentation](https://help.bolt.com/developers/references/bolt-oauth/#scopes).
	//
	Scope []Scope `form:"name=scope"`
	// A randomly generated string issued to the merchant when receiving an authorization code used to prevent CSRF attacks
	State *string `form:"name=state"`
}

func (o *GetAccessTokenRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *GetAccessTokenRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *GetAccessTokenRequest) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *GetAccessTokenRequest) GetGrantType() GrantType {
	if o == nil {
		return GrantType("")
	}
	return o.GrantType
}

func (o *GetAccessTokenRequest) GetScope() []Scope {
	if o == nil {
		return []Scope{}
	}
	return o.Scope
}

func (o *GetAccessTokenRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}
