// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/bolt-go/internal/utils"
)

type PaymentMethodType string

const (
	PaymentMethodTypeCreditCard PaymentMethodType = "credit_card"
	PaymentMethodTypePaypal     PaymentMethodType = "paypal"
)

type PaymentMethod struct {
	PaymentMethodCreditCard   *PaymentMethodCreditCard
	PaymentMethodPaypalOutput *PaymentMethodPaypalOutput

	Type PaymentMethodType
}

func CreatePaymentMethodCreditCard(creditCard PaymentMethodCreditCard) PaymentMethod {
	typ := PaymentMethodTypeCreditCard

	typStr := DotTag(typ)
	creditCard.DotTag = typStr

	return PaymentMethod{
		PaymentMethodCreditCard: &creditCard,
		Type:                    typ,
	}
}

func CreatePaymentMethodPaypal(paypal PaymentMethodPaypalOutput) PaymentMethod {
	typ := PaymentMethodTypePaypal

	typStr := PaymentMethodPaypalTag(typ)
	paypal.DotTag = typStr

	return PaymentMethod{
		PaymentMethodPaypalOutput: &paypal,
		Type:                      typ,
	}
}

func (u *PaymentMethod) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		DotTag string `json:".tag"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.DotTag {
	case "credit_card":
		paymentMethodCreditCard := new(PaymentMethodCreditCard)
		if err := utils.UnmarshalJSON(data, &paymentMethodCreditCard, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.PaymentMethodCreditCard = paymentMethodCreditCard
		u.Type = PaymentMethodTypeCreditCard
		return nil
	case "paypal":
		paymentMethodPaypalOutput := new(PaymentMethodPaypalOutput)
		if err := utils.UnmarshalJSON(data, &paymentMethodPaypalOutput, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.PaymentMethodPaypalOutput = paymentMethodPaypalOutput
		u.Type = PaymentMethodTypePaypal
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u PaymentMethod) MarshalJSON() ([]byte, error) {
	if u.PaymentMethodCreditCard != nil {
		return utils.MarshalJSON(u.PaymentMethodCreditCard, "", true)
	}

	if u.PaymentMethodPaypalOutput != nil {
		return utils.MarshalJSON(u.PaymentMethodPaypalOutput, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
