// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type PaymentInitializeRequest struct {
	Cart          Cart                  `json:"cart"`
	PaymentMethod PaymentMethodExtended `json:"payment_method"`
}

func (o *PaymentInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *PaymentInitializeRequest) GetPaymentMethod() PaymentMethodExtended {
	if o == nil {
		return PaymentMethodExtended{}
	}
	return o.PaymentMethod
}

func (o *PaymentInitializeRequest) GetPaymentMethodID() *PaymentMethodReference {
	return o.GetPaymentMethod().PaymentMethodReference
}

func (o *PaymentInitializeRequest) GetPaymentMethodCreditCard() *PaymentMethodCreditCardInput {
	return o.GetPaymentMethod().PaymentMethodCreditCardInput
}

func (o *PaymentInitializeRequest) GetPaymentMethodPaypal() *PaymentMethodPaypal {
	return o.GetPaymentMethod().PaymentMethodPaypal
}
