// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/bolt-go/internal/utils"
)

type PaymentMethodInputType string

const (
	PaymentMethodInputTypeCreditCard PaymentMethodInputType = "credit_card"
	PaymentMethodInputTypePaypal     PaymentMethodInputType = "paypal"
)

type PaymentMethodInput struct {
	PaymentMethodCreditCardInput *PaymentMethodCreditCardInput
	PaymentMethodPaypal          *PaymentMethodPaypal

	Type PaymentMethodInputType
}

func CreatePaymentMethodInputCreditCard(creditCard PaymentMethodCreditCardInput) PaymentMethodInput {
	typ := PaymentMethodInputTypeCreditCard

	typStr := DotTag(typ)
	creditCard.DotTag = typStr

	return PaymentMethodInput{
		PaymentMethodCreditCardInput: &creditCard,
		Type:                         typ,
	}
}

func CreatePaymentMethodInputPaypal(paypal PaymentMethodPaypal) PaymentMethodInput {
	typ := PaymentMethodInputTypePaypal

	typStr := PaymentMethodPaypalTag(typ)
	paypal.DotTag = typStr

	return PaymentMethodInput{
		PaymentMethodPaypal: &paypal,
		Type:                typ,
	}
}

func (u *PaymentMethodInput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		DotTag string
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.DotTag {
	case "credit_card":
		paymentMethodCreditCardInput := new(PaymentMethodCreditCardInput)
		if err := utils.UnmarshalJSON(data, &paymentMethodCreditCardInput, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.PaymentMethodCreditCardInput = paymentMethodCreditCardInput
		u.Type = PaymentMethodInputTypeCreditCard
		return nil
	case "paypal":
		paymentMethodPaypal := new(PaymentMethodPaypal)
		if err := utils.UnmarshalJSON(data, &paymentMethodPaypal, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.PaymentMethodPaypal = paymentMethodPaypal
		u.Type = PaymentMethodInputTypePaypal
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u PaymentMethodInput) MarshalJSON() ([]byte, error) {
	if u.PaymentMethodCreditCardInput != nil {
		return utils.MarshalJSON(u.PaymentMethodCreditCardInput, "", true)
	}

	if u.PaymentMethodPaypal != nil {
		return utils.MarshalJSON(u.PaymentMethodPaypal, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
